-- ScholarAI: initial database schema
-- Every table has Row Level Security (RLS) switched on.
-- "authenticated" = a logged-in student. "service_role" = our Edge Functions (server only).

-- ============================================================
-- 1. Content tables (same for every student, read-only for them)
-- ============================================================

create table public.exams (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,            -- e.g. 'NIMCET'
  name text not null,                   -- e.g. 'NIMCET — NIT MCA Common Entrance Test'
  sort_order int not null default 0
);

create table public.subjects (
  id uuid primary key default gen_random_uuid(),
  exam_id uuid not null references public.exams (id) on delete cascade,
  name text not null,
  sort_order int not null default 0
);

create table public.units (
  id uuid primary key default gen_random_uuid(),
  subject_id uuid not null references public.subjects (id) on delete cascade,
  name text not null,
  sort_order int not null default 0
);

-- Predefined quiz questions: 5 per round, rounds 1 and 2, for every unit.
-- (Round 3 is generated live by Gemini and is not stored here.)
create table public.questions (
  id uuid primary key default gen_random_uuid(),
  unit_id uuid not null references public.units (id) on delete cascade,
  round smallint not null check (round in (1, 2)),
  question text not null,
  options text[] not null check (array_length(options, 1) = 4),
  correct_index smallint not null check (correct_index between 0 and 3),
  sort_order int not null default 0
);

-- The short rotating list of Comfort Zone tasks.
create table public.challenges (
  id int generated by default as identity primary key,
  text text not null
);

-- YouTube search results, saved once per unit and shared by all students.
-- Only Edge Functions write here (with the project YouTube key).
create table public.unit_videos (
  id uuid primary key default gen_random_uuid(),
  unit_id uuid not null references public.units (id) on delete cascade,
  youtube_video_id text not null,
  title text not null,
  channel_title text,
  thumbnail_url text,
  sort_order int not null default 0,
  fetched_at timestamptz not null default now(),
  unique (unit_id, youtube_video_id)
);

-- ============================================================
-- 2. Student tables (each student sees only their own rows)
-- ============================================================

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  mode text not null default 'default' check (mode in ('default', 'exam')),
  exam_id uuid references public.exams (id) on delete set null,
  current_streak int not null default 0,
  best_streak int not null default 0,
  last_streak_date date,
  gemini_key_hint text,                 -- masked only, e.g. 'AIza…x9Qk'
  created_at timestamptz not null default now()
);

-- The full Gemini key. No policies + no grants = the browser can never read it.
-- Only Edge Functions (service_role) can read or write this table.
create table public.user_secrets (
  user_id uuid primary key references auth.users (id) on delete cascade,
  gemini_api_key text not null,
  updated_at timestamptz not null default now()
);

create table public.quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  unit_id uuid not null references public.units (id) on delete cascade,
  round smallint not null check (round between 1 and 3),
  score smallint not null,
  total smallint not null check (total > 0),
  percent numeric(5, 2) generated always as (score * 100.0 / total) stored,
  answers jsonb not null default '[]',
  created_at timestamptz not null default now(),
  check (score between 0 and total)
);

create table public.video_watch (
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  video_id uuid not null references public.unit_videos (id) on delete cascade,
  watched_percent smallint not null default 0 check (watched_percent between 0 and 100),
  updated_at timestamptz not null default now(),
  primary key (user_id, video_id)
);

-- "day" is the student's local date, sent by the app.
create table public.challenge_completions (
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  challenge_id int not null references public.challenges (id) on delete cascade,
  day date not null,
  completed_at timestamptz not null default now(),
  primary key (user_id, day, challenge_id)
);

-- Each student's book picks for one day (the once-a-day cache).
-- Written by an Edge Function using the student's own Gemini key.
create table public.daily_books (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  day date not null,
  kind text not null check (kind in ('fiction', 'non_fiction')),
  title text not null,
  author text not null,
  reason text not null,
  created_at timestamptz not null default now(),
  unique (user_id, day, kind)
);

-- ============================================================
-- 3. Unit progress (a view, calculated from quiz attempts)
-- A unit is complete when ANY round scored 60% or more.
-- ============================================================

create view public.unit_progress
with (security_invoker = true) as
select
  user_id,
  unit_id,
  bool_or(percent >= 60) as completed,
  max(percent) as best_percent,
  (array_agg(score order by created_at desc))[1] as last_score,
  (array_agg(total order by created_at desc))[1] as last_total,
  (array_agg(percent order by created_at desc))[1] as last_percent,
  max(created_at) as last_attempt_at
from public.quiz_attempts
group by user_id, unit_id;

-- ============================================================
-- 4. Create a profile automatically when someone signs up
-- ============================================================

create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Accounts that already existed before this migration also get a profile.
insert into public.profiles (id, display_name)
select id, split_part(email, '@', 1)
from auth.users
on conflict (id) do nothing;

-- ============================================================
-- 5. Security: switch on RLS and write the rules
-- ============================================================

alter table public.exams enable row level security;
alter table public.subjects enable row level security;
alter table public.units enable row level security;
alter table public.questions enable row level security;
alter table public.challenges enable row level security;
alter table public.unit_videos enable row level security;
alter table public.profiles enable row level security;
alter table public.user_secrets enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.video_watch enable row level security;
alter table public.challenge_completions enable row level security;
alter table public.daily_books enable row level security;

-- Content: any logged-in student can read.
create policy "read exams" on public.exams for select to authenticated using (true);
create policy "read subjects" on public.subjects for select to authenticated using (true);
create policy "read units" on public.units for select to authenticated using (true);
create policy "read questions" on public.questions for select to authenticated using (true);
create policy "read challenges" on public.challenges for select to authenticated using (true);
create policy "read unit videos" on public.unit_videos for select to authenticated using (true);

-- Student data: only your own rows.
create policy "read own profile" on public.profiles
  for select to authenticated using (id = auth.uid());
create policy "update own profile" on public.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

create policy "read own attempts" on public.quiz_attempts
  for select to authenticated using (user_id = auth.uid());
create policy "add own attempts" on public.quiz_attempts
  for insert to authenticated with check (user_id = auth.uid());

create policy "read own watch" on public.video_watch
  for select to authenticated using (user_id = auth.uid());
create policy "add own watch" on public.video_watch
  for insert to authenticated with check (user_id = auth.uid());
create policy "update own watch" on public.video_watch
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "read own completions" on public.challenge_completions
  for select to authenticated using (user_id = auth.uid());
create policy "add own completions" on public.challenge_completions
  for insert to authenticated with check (user_id = auth.uid());

create policy "read own books" on public.daily_books
  for select to authenticated using (user_id = auth.uid());

-- user_secrets: deliberately NO policies.

-- Table permissions: start from nothing, then give only what the app needs.
revoke all on all tables in schema public from anon, authenticated;

grant select on public.exams, public.subjects, public.units, public.questions,
  public.challenges, public.unit_videos to authenticated;
grant select on public.profiles to authenticated;
-- Students may change only these profile columns (not streak or key hint).
grant update (display_name, mode, exam_id) on public.profiles to authenticated;
grant select, insert on public.quiz_attempts to authenticated;
grant select, insert, update on public.video_watch to authenticated;
grant select, insert on public.challenge_completions to authenticated;
grant select on public.daily_books to authenticated;
grant select on public.unit_progress to authenticated;
